// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetOrganizationReader is a Reader for the GetOrganization structure.
type GetOrganizationReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetOrganizationReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {

	result := NewGetOrganizationDefault(response.Code())
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	if response.Code()/100 == 2 {
		return result, nil
	}
	return nil, result

}

// NewGetOrganizationDefault creates a GetOrganizationDefault with default headers values
func NewGetOrganizationDefault(code int) *GetOrganizationDefault {
	return &GetOrganizationDefault{
		_statusCode: code,
	}
}

/*GetOrganizationDefault handles this case with default header values.

stub description for swagger compliance
*/
type GetOrganizationDefault struct {
	_statusCode int
}

// Code gets the status code for the get organization default response
func (o *GetOrganizationDefault) Code() int {
	return o._statusCode
}

func (o *GetOrganizationDefault) Error() string {
	return fmt.Sprintf("[GET /api/v2/organizations][%d] GetOrganization default ", o._statusCode)
}

func (o *GetOrganizationDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
