// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetDailyNewParams creates a new GetDailyNewParams object
// with the default values initialized.
func NewGetDailyNewParams() *GetDailyNewParams {
	var (
		authorizationDefault    = string("Bearer {access_token}")
		responseBodyPathDefault = string("{organization_id}")
		buildDefault            = string("all")
		endDefault              = string("1481328000")
		startDefault            = string("1478736000")
	)
	return &GetDailyNewParams{
		Authorization:    &authorizationDefault,
		ResponseBodyPath: responseBodyPathDefault,
		Build:            &buildDefault,
		End:              &endDefault,
		Start:            &startDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewGetDailyNewParamsWithTimeout creates a new GetDailyNewParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetDailyNewParamsWithTimeout(timeout time.Duration) *GetDailyNewParams {
	var (
		authorizationDefault    = string("Bearer {access_token}")
		responseBodyPathDefault = string("{organization_id}")
		buildDefault            = string("all")
		endDefault              = string("1481328000")
		startDefault            = string("1478736000")
	)
	return &GetDailyNewParams{
		Authorization:    &authorizationDefault,
		ResponseBodyPath: responseBodyPathDefault,
		Build:            &buildDefault,
		End:              &endDefault,
		Start:            &startDefault,

		timeout: timeout,
	}
}

// NewGetDailyNewParamsWithContext creates a new GetDailyNewParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetDailyNewParamsWithContext(ctx context.Context) *GetDailyNewParams {
	var (
		authorizationDefault    = string("Bearer {access_token}")
		responseBodyPathDefault = string("{organization_id}")
		buildDefault            = string("all")
		endDefault              = string("1481328000")
		startDefault            = string("1478736000")
	)
	return &GetDailyNewParams{
		Authorization:    &authorizationDefault,
		ResponseBodyPath: responseBodyPathDefault,
		Build:            &buildDefault,
		End:              &endDefault,
		Start:            &startDefault,

		Context: ctx,
	}
}

// NewGetDailyNewParamsWithHTTPClient creates a new GetDailyNewParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetDailyNewParamsWithHTTPClient(client *http.Client) *GetDailyNewParams {
	var (
		authorizationDefault    = string("Bearer {access_token}")
		responseBodyPathDefault = string("{organization_id}")
		buildDefault            = string("all")
		endDefault              = string("1481328000")
		startDefault            = string("1478736000")
	)
	return &GetDailyNewParams{
		Authorization:    &authorizationDefault,
		ResponseBodyPath: responseBodyPathDefault,
		Build:            &buildDefault,
		End:              &endDefault,
		Start:            &startDefault,
		HTTPClient:       client,
	}
}

/*GetDailyNewParams contains all the parameters to send to the API endpoint
for the get daily new operation typically these are written to a http.Request
*/
type GetDailyNewParams struct {

	/*Authorization*/
	Authorization *string
	/*ResponseBodyPath*/
	ResponseBodyPath string
	/*AppID*/
	AppID string
	/*Build*/
	Build *string
	/*End*/
	End *string
	/*Start*/
	Start *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get daily new params
func (o *GetDailyNewParams) WithTimeout(timeout time.Duration) *GetDailyNewParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get daily new params
func (o *GetDailyNewParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get daily new params
func (o *GetDailyNewParams) WithContext(ctx context.Context) *GetDailyNewParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get daily new params
func (o *GetDailyNewParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get daily new params
func (o *GetDailyNewParams) WithHTTPClient(client *http.Client) *GetDailyNewParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get daily new params
func (o *GetDailyNewParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the get daily new params
func (o *GetDailyNewParams) WithAuthorization(authorization *string) *GetDailyNewParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the get daily new params
func (o *GetDailyNewParams) SetAuthorization(authorization *string) {
	o.Authorization = authorization
}

// WithResponseBodyPath adds the responseBodyPath to the get daily new params
func (o *GetDailyNewParams) WithResponseBodyPath(responseBodyPath string) *GetDailyNewParams {
	o.SetResponseBodyPath(responseBodyPath)
	return o
}

// SetResponseBodyPath adds the responseBodyPath to the get daily new params
func (o *GetDailyNewParams) SetResponseBodyPath(responseBodyPath string) {
	o.ResponseBodyPath = responseBodyPath
}

// WithAppID adds the appID to the get daily new params
func (o *GetDailyNewParams) WithAppID(appID string) *GetDailyNewParams {
	o.SetAppID(appID)
	return o
}

// SetAppID adds the appId to the get daily new params
func (o *GetDailyNewParams) SetAppID(appID string) {
	o.AppID = appID
}

// WithBuild adds the build to the get daily new params
func (o *GetDailyNewParams) WithBuild(build *string) *GetDailyNewParams {
	o.SetBuild(build)
	return o
}

// SetBuild adds the build to the get daily new params
func (o *GetDailyNewParams) SetBuild(build *string) {
	o.Build = build
}

// WithEnd adds the end to the get daily new params
func (o *GetDailyNewParams) WithEnd(end *string) *GetDailyNewParams {
	o.SetEnd(end)
	return o
}

// SetEnd adds the end to the get daily new params
func (o *GetDailyNewParams) SetEnd(end *string) {
	o.End = end
}

// WithStart adds the start to the get daily new params
func (o *GetDailyNewParams) WithStart(start *string) *GetDailyNewParams {
	o.SetStart(start)
	return o
}

// SetStart adds the start to the get daily new params
func (o *GetDailyNewParams) SetStart(start *string) {
	o.Start = start
}

// WriteToRequest writes these params to a swagger request
func (o *GetDailyNewParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Authorization != nil {

		// header param Authorization
		if err := r.SetHeaderParam("Authorization", *o.Authorization); err != nil {
			return err
		}

	}

	// path param ResponseBodyPath
	if err := r.SetPathParam("ResponseBodyPath", o.ResponseBodyPath); err != nil {
		return err
	}

	// path param app_id
	if err := r.SetPathParam("app_id", o.AppID); err != nil {
		return err
	}

	if o.Build != nil {

		// query param build
		var qrBuild string
		if o.Build != nil {
			qrBuild = *o.Build
		}
		qBuild := qrBuild
		if qBuild != "" {
			if err := r.SetQueryParam("build", qBuild); err != nil {
				return err
			}
		}

	}

	if o.End != nil {

		// query param end
		var qrEnd string
		if o.End != nil {
			qrEnd = *o.End
		}
		qEnd := qrEnd
		if qEnd != "" {
			if err := r.SetQueryParam("end", qEnd); err != nil {
				return err
			}
		}

	}

	if o.Start != nil {

		// query param start
		var qrStart string
		if o.Start != nil {
			qrStart = *o.Start
		}
		qStart := qrStart
		if qStart != "" {
			if err := r.SetQueryParam("start", qStart); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
