// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetSingleBuildReader is a Reader for the GetSingleBuild structure.
type GetSingleBuildReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetSingleBuildReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {

	result := NewGetSingleBuildDefault(response.Code())
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	if response.Code()/100 == 2 {
		return result, nil
	}
	return nil, result

}

// NewGetSingleBuildDefault creates a GetSingleBuildDefault with default headers values
func NewGetSingleBuildDefault(code int) *GetSingleBuildDefault {
	return &GetSingleBuildDefault{
		_statusCode: code,
	}
}

/*GetSingleBuildDefault handles this case with default header values.

stub description for swagger compliance
*/
type GetSingleBuildDefault struct {
	_statusCode int
}

// Code gets the status code for the get single build default response
func (o *GetSingleBuildDefault) Code() int {
	return o._statusCode
}

func (o *GetSingleBuildDefault) Error() string {
	return fmt.Sprintf("[GET /api/v2/organizations/{ResponseBodyPath}/apps/{app_id}/beta_distribution/releases][%d] GetSingleBuild default ", o._statusCode)
}

func (o *GetSingleBuildDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
