// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetAllAppsReader is a Reader for the GetAllApps structure.
type GetAllAppsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAllAppsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {

	result := NewGetAllAppsDefault(response.Code())
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	if response.Code()/100 == 2 {
		return result, nil
	}
	return nil, result

}

// NewGetAllAppsDefault creates a GetAllAppsDefault with default headers values
func NewGetAllAppsDefault(code int) *GetAllAppsDefault {
	return &GetAllAppsDefault{
		_statusCode: code,
	}
}

/*GetAllAppsDefault handles this case with default header values.

stub description for swagger compliance
*/
type GetAllAppsDefault struct {
	_statusCode int
}

// Code gets the status code for the get all apps default response
func (o *GetAllAppsDefault) Code() int {
	return o._statusCode
}

func (o *GetAllAppsDefault) Error() string {
	return fmt.Sprintf("[GET /api/v2/apps][%d] GetAllApps default ", o._statusCode)
}

func (o *GetAllAppsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
