// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetAllBuildsReader is a Reader for the GetAllBuilds structure.
type GetAllBuildsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAllBuildsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {

	result := NewGetAllBuildsDefault(response.Code())
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	if response.Code()/100 == 2 {
		return result, nil
	}
	return nil, result

}

// NewGetAllBuildsDefault creates a GetAllBuildsDefault with default headers values
func NewGetAllBuildsDefault(code int) *GetAllBuildsDefault {
	return &GetAllBuildsDefault{
		_statusCode: code,
	}
}

/*GetAllBuildsDefault handles this case with default header values.

stub description for swagger compliance
*/
type GetAllBuildsDefault struct {
	_statusCode int
}

// Code gets the status code for the get all builds default response
func (o *GetAllBuildsDefault) Code() int {
	return o._statusCode
}

func (o *GetAllBuildsDefault) Error() string {
	return fmt.Sprintf("[GET /api/v2/organizations/{ResponseBodyPath}/apps/{app_id}/beta_distribution/releases/{release_id}][%d] GetAllBuilds default ", o._statusCode)
}

func (o *GetAllBuildsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
