// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetSessionCountReader is a Reader for the GetSessionCount structure.
type GetSessionCountReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetSessionCountReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {

	result := NewGetSessionCountDefault(response.Code())
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	if response.Code()/100 == 2 {
		return result, nil
	}
	return nil, result

}

// NewGetSessionCountDefault creates a GetSessionCountDefault with default headers values
func NewGetSessionCountDefault(code int) *GetSessionCountDefault {
	return &GetSessionCountDefault{
		_statusCode: code,
	}
}

/*GetSessionCountDefault handles this case with default header values.

stub description for swagger compliance
*/
type GetSessionCountDefault struct {
	_statusCode int
}

// Code gets the status code for the get session count default response
func (o *GetSessionCountDefault) Code() int {
	return o._statusCode
}

func (o *GetSessionCountDefault) Error() string {
	return fmt.Sprintf("[GET /api/v2/organizations/{ResponseBodyPath}/apps/{app_id}/growth_analytics/total_sessions_scalar.json][%d] GetSessionCount default ", o._statusCode)
}

func (o *GetSessionCountDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
