// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetDailyActiveReader is a Reader for the GetDailyActive structure.
type GetDailyActiveReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetDailyActiveReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {

	result := NewGetDailyActiveDefault(response.Code())
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	if response.Code()/100 == 2 {
		return result, nil
	}
	return nil, result

}

// NewGetDailyActiveDefault creates a GetDailyActiveDefault with default headers values
func NewGetDailyActiveDefault(code int) *GetDailyActiveDefault {
	return &GetDailyActiveDefault{
		_statusCode: code,
	}
}

/*GetDailyActiveDefault handles this case with default header values.

stub description for swagger compliance
*/
type GetDailyActiveDefault struct {
	_statusCode int
}

// Code gets the status code for the get daily active default response
func (o *GetDailyActiveDefault) Code() int {
	return o._statusCode
}

func (o *GetDailyActiveDefault) Error() string {
	return fmt.Sprintf("[GET /api/v2/organizations/{ResponseBodyPath}/apps/{app_id}/growth_analytics/daily_active.json][%d] GetDailyActive default ", o._statusCode)
}

func (o *GetDailyActiveDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
