// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetOOMReader is a Reader for the GetOOM structure.
type GetOOMReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetOOMReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {

	result := NewGetOOMDefault(response.Code())
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	if response.Code()/100 == 2 {
		return result, nil
	}
	return nil, result

}

// NewGetOOMDefault creates a GetOOMDefault with default headers values
func NewGetOOMDefault(code int) *GetOOMDefault {
	return &GetOOMDefault{
		_statusCode: code,
	}
}

/*GetOOMDefault handles this case with default header values.

stub description for swagger compliance
*/
type GetOOMDefault struct {
	_statusCode int
}

// Code gets the status code for the get o o m default response
func (o *GetOOMDefault) Code() int {
	return o._statusCode
}

func (o *GetOOMDefault) Error() string {
	return fmt.Sprintf("[POST /graphql][%d] GetOOM default ", o._statusCode)
}

func (o *GetOOMDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
