// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetOrganizationParams creates a new GetOrganizationParams object
// with the default values initialized.
func NewGetOrganizationParams() *GetOrganizationParams {
	var (
		authorizationDefault = string("Bearer {access_token}")
	)
	return &GetOrganizationParams{
		Authorization: &authorizationDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewGetOrganizationParamsWithTimeout creates a new GetOrganizationParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetOrganizationParamsWithTimeout(timeout time.Duration) *GetOrganizationParams {
	var (
		authorizationDefault = string("Bearer {access_token}")
	)
	return &GetOrganizationParams{
		Authorization: &authorizationDefault,

		timeout: timeout,
	}
}

// NewGetOrganizationParamsWithContext creates a new GetOrganizationParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetOrganizationParamsWithContext(ctx context.Context) *GetOrganizationParams {
	var (
		authorizationDefault = string("Bearer {access_token}")
	)
	return &GetOrganizationParams{
		Authorization: &authorizationDefault,

		Context: ctx,
	}
}

// NewGetOrganizationParamsWithHTTPClient creates a new GetOrganizationParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetOrganizationParamsWithHTTPClient(client *http.Client) *GetOrganizationParams {
	var (
		authorizationDefault = string("Bearer {access_token}")
	)
	return &GetOrganizationParams{
		Authorization: &authorizationDefault,
		HTTPClient:    client,
	}
}

/*GetOrganizationParams contains all the parameters to send to the API endpoint
for the get organization operation typically these are written to a http.Request
*/
type GetOrganizationParams struct {

	/*Authorization*/
	Authorization *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get organization params
func (o *GetOrganizationParams) WithTimeout(timeout time.Duration) *GetOrganizationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get organization params
func (o *GetOrganizationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get organization params
func (o *GetOrganizationParams) WithContext(ctx context.Context) *GetOrganizationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get organization params
func (o *GetOrganizationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get organization params
func (o *GetOrganizationParams) WithHTTPClient(client *http.Client) *GetOrganizationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get organization params
func (o *GetOrganizationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the get organization params
func (o *GetOrganizationParams) WithAuthorization(authorization *string) *GetOrganizationParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the get organization params
func (o *GetOrganizationParams) SetAuthorization(authorization *string) {
	o.Authorization = authorization
}

// WriteToRequest writes these params to a swagger request
func (o *GetOrganizationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Authorization != nil {

		// header param Authorization
		if err := r.SetHeaderParam("Authorization", *o.Authorization); err != nil {
			return err
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
