// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// OAuthReader is a Reader for the OAuth structure.
type OAuthReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *OAuthReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {

	result := NewOAuthDefault(response.Code())
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	if response.Code()/100 == 2 {
		return result, nil
	}
	return nil, result

}

// NewOAuthDefault creates a OAuthDefault with default headers values
func NewOAuthDefault(code int) *OAuthDefault {
	return &OAuthDefault{
		_statusCode: code,
	}
}

/*OAuthDefault handles this case with default header values.

stub description for swagger compliance
*/
type OAuthDefault struct {
	_statusCode int
}

// Code gets the status code for the o auth default response
func (o *OAuthDefault) Code() int {
	return o._statusCode
}

func (o *OAuthDefault) Error() string {
	return fmt.Sprintf("[POST /oauth/token][%d] OAuth default ", o._statusCode)
}

func (o *OAuthDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
