// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/TommyO/fabric.io/models"
)

// ActiveReader is a Reader for the Active structure.
type ActiveReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ActiveReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewActiveOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewActiveOK creates a ActiveOK with default headers values
func NewActiveOK() *ActiveOK {
	return &ActiveOK{}
}

/*ActiveOK handles this case with default header values.

Report
*/
type ActiveOK struct {
	Payload *models.ActiveOKBody
}

func (o *ActiveOK) Error() string {
	return fmt.Sprintf("[GET /api/v2/organizations/{organization_id}/apps/{app_id}/growth_analytics/{period}_active.json][%d] activeOK  %+v", 200, o.Payload)
}

func (o *ActiveOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ActiveOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
