// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewActiveParams creates a new ActiveParams object
// with the default values initialized.
func NewActiveParams() *ActiveParams {
	var (
		buildDefault = string("all")
	)
	return &ActiveParams{
		Build: &buildDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewActiveParamsWithTimeout creates a new ActiveParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewActiveParamsWithTimeout(timeout time.Duration) *ActiveParams {
	var (
		buildDefault = string("all")
	)
	return &ActiveParams{
		Build: &buildDefault,

		timeout: timeout,
	}
}

// NewActiveParamsWithContext creates a new ActiveParams object
// with the default values initialized, and the ability to set a context for a request
func NewActiveParamsWithContext(ctx context.Context) *ActiveParams {
	var (
		buildDefault = string("all")
	)
	return &ActiveParams{
		Build: &buildDefault,

		Context: ctx,
	}
}

// NewActiveParamsWithHTTPClient creates a new ActiveParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewActiveParamsWithHTTPClient(client *http.Client) *ActiveParams {
	var (
		buildDefault = string("all")
	)
	return &ActiveParams{
		Build:      &buildDefault,
		HTTPClient: client,
	}
}

/*ActiveParams contains all the parameters to send to the API endpoint
for the active operation typically these are written to a http.Request
*/
type ActiveParams struct {

	/*Authorization*/
	Authorization string
	/*AppID*/
	AppID string
	/*Build*/
	Build *string
	/*End*/
	End *float64
	/*OrganizationID*/
	OrganizationID string
	/*Period*/
	Period string
	/*Start*/
	Start *float64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the active params
func (o *ActiveParams) WithTimeout(timeout time.Duration) *ActiveParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the active params
func (o *ActiveParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the active params
func (o *ActiveParams) WithContext(ctx context.Context) *ActiveParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the active params
func (o *ActiveParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the active params
func (o *ActiveParams) WithHTTPClient(client *http.Client) *ActiveParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the active params
func (o *ActiveParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the active params
func (o *ActiveParams) WithAuthorization(authorization string) *ActiveParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the active params
func (o *ActiveParams) SetAuthorization(authorization string) {
	o.Authorization = authorization
}

// WithAppID adds the appID to the active params
func (o *ActiveParams) WithAppID(appID string) *ActiveParams {
	o.SetAppID(appID)
	return o
}

// SetAppID adds the appId to the active params
func (o *ActiveParams) SetAppID(appID string) {
	o.AppID = appID
}

// WithBuild adds the build to the active params
func (o *ActiveParams) WithBuild(build *string) *ActiveParams {
	o.SetBuild(build)
	return o
}

// SetBuild adds the build to the active params
func (o *ActiveParams) SetBuild(build *string) {
	o.Build = build
}

// WithEnd adds the end to the active params
func (o *ActiveParams) WithEnd(end *float64) *ActiveParams {
	o.SetEnd(end)
	return o
}

// SetEnd adds the end to the active params
func (o *ActiveParams) SetEnd(end *float64) {
	o.End = end
}

// WithOrganizationID adds the organizationID to the active params
func (o *ActiveParams) WithOrganizationID(organizationID string) *ActiveParams {
	o.SetOrganizationID(organizationID)
	return o
}

// SetOrganizationID adds the organizationId to the active params
func (o *ActiveParams) SetOrganizationID(organizationID string) {
	o.OrganizationID = organizationID
}

// WithPeriod adds the period to the active params
func (o *ActiveParams) WithPeriod(period string) *ActiveParams {
	o.SetPeriod(period)
	return o
}

// SetPeriod adds the period to the active params
func (o *ActiveParams) SetPeriod(period string) {
	o.Period = period
}

// WithStart adds the start to the active params
func (o *ActiveParams) WithStart(start *float64) *ActiveParams {
	o.SetStart(start)
	return o
}

// SetStart adds the start to the active params
func (o *ActiveParams) SetStart(start *float64) {
	o.Start = start
}

// WriteToRequest writes these params to a swagger request
func (o *ActiveParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Authorization
	if err := r.SetHeaderParam("Authorization", o.Authorization); err != nil {
		return err
	}

	// path param app_id
	if err := r.SetPathParam("app_id", o.AppID); err != nil {
		return err
	}

	if o.Build != nil {

		// query param build
		var qrBuild string
		if o.Build != nil {
			qrBuild = *o.Build
		}
		qBuild := qrBuild
		if qBuild != "" {
			if err := r.SetQueryParam("build", qBuild); err != nil {
				return err
			}
		}

	}

	if o.End != nil {

		// query param end
		var qrEnd float64
		if o.End != nil {
			qrEnd = *o.End
		}
		qEnd := swag.FormatFloat64(qrEnd)
		if qEnd != "" {
			if err := r.SetQueryParam("end", qEnd); err != nil {
				return err
			}
		}

	}

	// path param organization_id
	if err := r.SetPathParam("organization_id", o.OrganizationID); err != nil {
		return err
	}

	// path param period
	if err := r.SetPathParam("period", o.Period); err != nil {
		return err
	}

	if o.Start != nil {

		// query param start
		var qrStart float64
		if o.Start != nil {
			qrStart = *o.Start
		}
		qStart := swag.FormatFloat64(qrStart)
		if qStart != "" {
			if err := r.SetQueryParam("start", qStart); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
