// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/TommyO/fabric.io/models"
)

// AppReader is a Reader for the App structure.
type AppReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AppReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewAppOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewAppOK creates a AppOK with default headers values
func NewAppOK() *AppOK {
	return &AppOK{}
}

/*AppOK handles this case with default header values.

app details
*/
type AppOK struct {
	Payload *models.App
}

func (o *AppOK) Error() string {
	return fmt.Sprintf("[GET /api/v2/apps/{app_id}][%d] appOK  %+v", 200, o.Payload)
}

func (o *AppOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.App)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
