// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/TommyO/fabric.io/models"
)

// DailyNewReader is a Reader for the DailyNew structure.
type DailyNewReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DailyNewReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDailyNewOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDailyNewOK creates a DailyNewOK with default headers values
func NewDailyNewOK() *DailyNewOK {
	return &DailyNewOK{}
}

/*DailyNewOK handles this case with default header values.

Report
*/
type DailyNewOK struct {
	Payload *models.DailyNewOKBody
}

func (o *DailyNewOK) Error() string {
	return fmt.Sprintf("[GET /api/v2/organizations/{organization_id}/apps/{app_id}/growth_analytics/daily_new.json][%d] dailyNewOK  %+v", 200, o.Payload)
}

func (o *DailyNewOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DailyNewOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
