// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetActiveNowParams creates a new GetActiveNowParams object
// with the default values initialized.
func NewGetActiveNowParams() *GetActiveNowParams {
	var (
		authorizationDefault    = string("Bearer {access_token}")
		responseBodyPathDefault = string("{organization_id}")
		buildDefault            = string("all")
	)
	return &GetActiveNowParams{
		Authorization:    &authorizationDefault,
		ResponseBodyPath: responseBodyPathDefault,
		Build:            &buildDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewGetActiveNowParamsWithTimeout creates a new GetActiveNowParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetActiveNowParamsWithTimeout(timeout time.Duration) *GetActiveNowParams {
	var (
		authorizationDefault    = string("Bearer {access_token}")
		responseBodyPathDefault = string("{organization_id}")
		buildDefault            = string("all")
	)
	return &GetActiveNowParams{
		Authorization:    &authorizationDefault,
		ResponseBodyPath: responseBodyPathDefault,
		Build:            &buildDefault,

		timeout: timeout,
	}
}

// NewGetActiveNowParamsWithContext creates a new GetActiveNowParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetActiveNowParamsWithContext(ctx context.Context) *GetActiveNowParams {
	var (
		authorizationDefault    = string("Bearer {access_token}")
		responseBodyPathDefault = string("{organization_id}")
		buildDefault            = string("all")
	)
	return &GetActiveNowParams{
		Authorization:    &authorizationDefault,
		ResponseBodyPath: responseBodyPathDefault,
		Build:            &buildDefault,

		Context: ctx,
	}
}

// NewGetActiveNowParamsWithHTTPClient creates a new GetActiveNowParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetActiveNowParamsWithHTTPClient(client *http.Client) *GetActiveNowParams {
	var (
		authorizationDefault    = string("Bearer {access_token}")
		responseBodyPathDefault = string("{organization_id}")
		buildDefault            = string("all")
	)
	return &GetActiveNowParams{
		Authorization:    &authorizationDefault,
		ResponseBodyPath: responseBodyPathDefault,
		Build:            &buildDefault,
		HTTPClient:       client,
	}
}

/*GetActiveNowParams contains all the parameters to send to the API endpoint
for the get active now operation typically these are written to a http.Request
*/
type GetActiveNowParams struct {

	/*Authorization*/
	Authorization *string
	/*ResponseBodyPath*/
	ResponseBodyPath string
	/*AppID*/
	AppID string
	/*Build*/
	Build *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get active now params
func (o *GetActiveNowParams) WithTimeout(timeout time.Duration) *GetActiveNowParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get active now params
func (o *GetActiveNowParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get active now params
func (o *GetActiveNowParams) WithContext(ctx context.Context) *GetActiveNowParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get active now params
func (o *GetActiveNowParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get active now params
func (o *GetActiveNowParams) WithHTTPClient(client *http.Client) *GetActiveNowParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get active now params
func (o *GetActiveNowParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the get active now params
func (o *GetActiveNowParams) WithAuthorization(authorization *string) *GetActiveNowParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the get active now params
func (o *GetActiveNowParams) SetAuthorization(authorization *string) {
	o.Authorization = authorization
}

// WithResponseBodyPath adds the responseBodyPath to the get active now params
func (o *GetActiveNowParams) WithResponseBodyPath(responseBodyPath string) *GetActiveNowParams {
	o.SetResponseBodyPath(responseBodyPath)
	return o
}

// SetResponseBodyPath adds the responseBodyPath to the get active now params
func (o *GetActiveNowParams) SetResponseBodyPath(responseBodyPath string) {
	o.ResponseBodyPath = responseBodyPath
}

// WithAppID adds the appID to the get active now params
func (o *GetActiveNowParams) WithAppID(appID string) *GetActiveNowParams {
	o.SetAppID(appID)
	return o
}

// SetAppID adds the appId to the get active now params
func (o *GetActiveNowParams) SetAppID(appID string) {
	o.AppID = appID
}

// WithBuild adds the build to the get active now params
func (o *GetActiveNowParams) WithBuild(build *string) *GetActiveNowParams {
	o.SetBuild(build)
	return o
}

// SetBuild adds the build to the get active now params
func (o *GetActiveNowParams) SetBuild(build *string) {
	o.Build = build
}

// WriteToRequest writes these params to a swagger request
func (o *GetActiveNowParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Authorization != nil {

		// header param Authorization
		if err := r.SetHeaderParam("Authorization", *o.Authorization); err != nil {
			return err
		}

	}

	// path param ResponseBodyPath
	if err := r.SetPathParam("ResponseBodyPath", o.ResponseBodyPath); err != nil {
		return err
	}

	// path param app_id
	if err := r.SetPathParam("app_id", o.AppID); err != nil {
		return err
	}

	if o.Build != nil {

		// query param build
		var qrBuild string
		if o.Build != nil {
			qrBuild = *o.Build
		}
		qBuild := qrBuild
		if qBuild != "" {
			if err := r.SetQueryParam("build", qBuild); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
