// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetTopBuildsParams creates a new GetTopBuildsParams object
// with the default values initialized.
func NewGetTopBuildsParams() *GetTopBuildsParams {
	var (
		authorizationDefault    = string("Bearer {access_token}")
		responseBodyPathDefault = string("{organization_id}")
		endDefault              = string("1481328000")
		startDefault            = string("0")
	)
	return &GetTopBuildsParams{
		Authorization:    &authorizationDefault,
		ResponseBodyPath: responseBodyPathDefault,
		End:              &endDefault,
		Start:            &startDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewGetTopBuildsParamsWithTimeout creates a new GetTopBuildsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetTopBuildsParamsWithTimeout(timeout time.Duration) *GetTopBuildsParams {
	var (
		authorizationDefault    = string("Bearer {access_token}")
		responseBodyPathDefault = string("{organization_id}")
		endDefault              = string("1481328000")
		startDefault            = string("0")
	)
	return &GetTopBuildsParams{
		Authorization:    &authorizationDefault,
		ResponseBodyPath: responseBodyPathDefault,
		End:              &endDefault,
		Start:            &startDefault,

		timeout: timeout,
	}
}

// NewGetTopBuildsParamsWithContext creates a new GetTopBuildsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetTopBuildsParamsWithContext(ctx context.Context) *GetTopBuildsParams {
	var (
		authorizationDefault    = string("Bearer {access_token}")
		responseBodyPathDefault = string("{organization_id}")
		endDefault              = string("1481328000")
		startDefault            = string("0")
	)
	return &GetTopBuildsParams{
		Authorization:    &authorizationDefault,
		ResponseBodyPath: responseBodyPathDefault,
		End:              &endDefault,
		Start:            &startDefault,

		Context: ctx,
	}
}

// NewGetTopBuildsParamsWithHTTPClient creates a new GetTopBuildsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetTopBuildsParamsWithHTTPClient(client *http.Client) *GetTopBuildsParams {
	var (
		authorizationDefault    = string("Bearer {access_token}")
		responseBodyPathDefault = string("{organization_id}")
		endDefault              = string("1481328000")
		startDefault            = string("0")
	)
	return &GetTopBuildsParams{
		Authorization:    &authorizationDefault,
		ResponseBodyPath: responseBodyPathDefault,
		End:              &endDefault,
		Start:            &startDefault,
		HTTPClient:       client,
	}
}

/*GetTopBuildsParams contains all the parameters to send to the API endpoint
for the get top builds operation typically these are written to a http.Request
*/
type GetTopBuildsParams struct {

	/*Authorization*/
	Authorization *string
	/*ResponseBodyPath*/
	ResponseBodyPath string
	/*AppID*/
	AppID string
	/*End*/
	End *string
	/*Start*/
	Start *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get top builds params
func (o *GetTopBuildsParams) WithTimeout(timeout time.Duration) *GetTopBuildsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get top builds params
func (o *GetTopBuildsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get top builds params
func (o *GetTopBuildsParams) WithContext(ctx context.Context) *GetTopBuildsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get top builds params
func (o *GetTopBuildsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get top builds params
func (o *GetTopBuildsParams) WithHTTPClient(client *http.Client) *GetTopBuildsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get top builds params
func (o *GetTopBuildsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the get top builds params
func (o *GetTopBuildsParams) WithAuthorization(authorization *string) *GetTopBuildsParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the get top builds params
func (o *GetTopBuildsParams) SetAuthorization(authorization *string) {
	o.Authorization = authorization
}

// WithResponseBodyPath adds the responseBodyPath to the get top builds params
func (o *GetTopBuildsParams) WithResponseBodyPath(responseBodyPath string) *GetTopBuildsParams {
	o.SetResponseBodyPath(responseBodyPath)
	return o
}

// SetResponseBodyPath adds the responseBodyPath to the get top builds params
func (o *GetTopBuildsParams) SetResponseBodyPath(responseBodyPath string) {
	o.ResponseBodyPath = responseBodyPath
}

// WithAppID adds the appID to the get top builds params
func (o *GetTopBuildsParams) WithAppID(appID string) *GetTopBuildsParams {
	o.SetAppID(appID)
	return o
}

// SetAppID adds the appId to the get top builds params
func (o *GetTopBuildsParams) SetAppID(appID string) {
	o.AppID = appID
}

// WithEnd adds the end to the get top builds params
func (o *GetTopBuildsParams) WithEnd(end *string) *GetTopBuildsParams {
	o.SetEnd(end)
	return o
}

// SetEnd adds the end to the get top builds params
func (o *GetTopBuildsParams) SetEnd(end *string) {
	o.End = end
}

// WithStart adds the start to the get top builds params
func (o *GetTopBuildsParams) WithStart(start *string) *GetTopBuildsParams {
	o.SetStart(start)
	return o
}

// SetStart adds the start to the get top builds params
func (o *GetTopBuildsParams) SetStart(start *string) {
	o.Start = start
}

// WriteToRequest writes these params to a swagger request
func (o *GetTopBuildsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Authorization != nil {

		// header param Authorization
		if err := r.SetHeaderParam("Authorization", *o.Authorization); err != nil {
			return err
		}

	}

	// path param ResponseBodyPath
	if err := r.SetPathParam("ResponseBodyPath", o.ResponseBodyPath); err != nil {
		return err
	}

	// path param app_id
	if err := r.SetPathParam("app_id", o.AppID); err != nil {
		return err
	}

	if o.End != nil {

		// query param end
		var qrEnd string
		if o.End != nil {
			qrEnd = *o.End
		}
		qEnd := qrEnd
		if qEnd != "" {
			if err := r.SetQueryParam("end", qEnd); err != nil {
				return err
			}
		}

	}

	if o.Start != nil {

		// query param start
		var qrStart string
		if o.Start != nil {
			qrStart = *o.Start
		}
		qStart := qrStart
		if qStart != "" {
			if err := r.SetQueryParam("start", qStart); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
