// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetSingleAppReader is a Reader for the GetSingleApp structure.
type GetSingleAppReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetSingleAppReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {

	result := NewGetSingleAppDefault(response.Code())
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	if response.Code()/100 == 2 {
		return result, nil
	}
	return nil, result

}

// NewGetSingleAppDefault creates a GetSingleAppDefault with default headers values
func NewGetSingleAppDefault(code int) *GetSingleAppDefault {
	return &GetSingleAppDefault{
		_statusCode: code,
	}
}

/*GetSingleAppDefault handles this case with default header values.

stub description for swagger compliance
*/
type GetSingleAppDefault struct {
	_statusCode int
}

// Code gets the status code for the get single app default response
func (o *GetSingleAppDefault) Code() int {
	return o._statusCode
}

func (o *GetSingleAppDefault) Error() string {
	return fmt.Sprintf("[GET /api/v2/apps/{app_id}][%d] GetSingleApp default ", o._statusCode)
}

func (o *GetSingleAppDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
