// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetAllAppsParams creates a new GetAllAppsParams object
// with the default values initialized.
func NewGetAllAppsParams() *GetAllAppsParams {
	var (
		authorizationDefault = string("Bearer {access_token}")
	)
	return &GetAllAppsParams{
		Authorization: &authorizationDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAllAppsParamsWithTimeout creates a new GetAllAppsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAllAppsParamsWithTimeout(timeout time.Duration) *GetAllAppsParams {
	var (
		authorizationDefault = string("Bearer {access_token}")
	)
	return &GetAllAppsParams{
		Authorization: &authorizationDefault,

		timeout: timeout,
	}
}

// NewGetAllAppsParamsWithContext creates a new GetAllAppsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetAllAppsParamsWithContext(ctx context.Context) *GetAllAppsParams {
	var (
		authorizationDefault = string("Bearer {access_token}")
	)
	return &GetAllAppsParams{
		Authorization: &authorizationDefault,

		Context: ctx,
	}
}

// NewGetAllAppsParamsWithHTTPClient creates a new GetAllAppsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetAllAppsParamsWithHTTPClient(client *http.Client) *GetAllAppsParams {
	var (
		authorizationDefault = string("Bearer {access_token}")
	)
	return &GetAllAppsParams{
		Authorization: &authorizationDefault,
		HTTPClient:    client,
	}
}

/*GetAllAppsParams contains all the parameters to send to the API endpoint
for the get all apps operation typically these are written to a http.Request
*/
type GetAllAppsParams struct {

	/*Authorization*/
	Authorization *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get all apps params
func (o *GetAllAppsParams) WithTimeout(timeout time.Duration) *GetAllAppsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get all apps params
func (o *GetAllAppsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get all apps params
func (o *GetAllAppsParams) WithContext(ctx context.Context) *GetAllAppsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get all apps params
func (o *GetAllAppsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get all apps params
func (o *GetAllAppsParams) WithHTTPClient(client *http.Client) *GetAllAppsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get all apps params
func (o *GetAllAppsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the get all apps params
func (o *GetAllAppsParams) WithAuthorization(authorization *string) *GetAllAppsParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the get all apps params
func (o *GetAllAppsParams) SetAuthorization(authorization *string) {
	o.Authorization = authorization
}

// WriteToRequest writes these params to a swagger request
func (o *GetAllAppsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Authorization != nil {

		// header param Authorization
		if err := r.SetHeaderParam("Authorization", *o.Authorization); err != nil {
			return err
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
