// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetActiveNowReader is a Reader for the GetActiveNow structure.
type GetActiveNowReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetActiveNowReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {

	result := NewGetActiveNowDefault(response.Code())
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	if response.Code()/100 == 2 {
		return result, nil
	}
	return nil, result

}

// NewGetActiveNowDefault creates a GetActiveNowDefault with default headers values
func NewGetActiveNowDefault(code int) *GetActiveNowDefault {
	return &GetActiveNowDefault{
		_statusCode: code,
	}
}

/*GetActiveNowDefault handles this case with default header values.

stub description for swagger compliance
*/
type GetActiveNowDefault struct {
	_statusCode int
}

// Code gets the status code for the get active now default response
func (o *GetActiveNowDefault) Code() int {
	return o._statusCode
}

func (o *GetActiveNowDefault) Error() string {
	return fmt.Sprintf("[GET /api/v2/organizations/{ResponseBodyPath}/apps/{app_id}/growth_analytics/active_now.json][%d] GetActiveNow default ", o._statusCode)
}

func (o *GetActiveNowDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
