// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewOrganizationsParams creates a new OrganizationsParams object
// with the default values initialized.
func NewOrganizationsParams() *OrganizationsParams {
	var ()
	return &OrganizationsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewOrganizationsParamsWithTimeout creates a new OrganizationsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewOrganizationsParamsWithTimeout(timeout time.Duration) *OrganizationsParams {
	var ()
	return &OrganizationsParams{

		timeout: timeout,
	}
}

// NewOrganizationsParamsWithContext creates a new OrganizationsParams object
// with the default values initialized, and the ability to set a context for a request
func NewOrganizationsParamsWithContext(ctx context.Context) *OrganizationsParams {
	var ()
	return &OrganizationsParams{

		Context: ctx,
	}
}

// NewOrganizationsParamsWithHTTPClient creates a new OrganizationsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewOrganizationsParamsWithHTTPClient(client *http.Client) *OrganizationsParams {
	var ()
	return &OrganizationsParams{
		HTTPClient: client,
	}
}

/*OrganizationsParams contains all the parameters to send to the API endpoint
for the organizations operation typically these are written to a http.Request
*/
type OrganizationsParams struct {

	/*Authorization*/
	Authorization string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the organizations params
func (o *OrganizationsParams) WithTimeout(timeout time.Duration) *OrganizationsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the organizations params
func (o *OrganizationsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the organizations params
func (o *OrganizationsParams) WithContext(ctx context.Context) *OrganizationsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the organizations params
func (o *OrganizationsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the organizations params
func (o *OrganizationsParams) WithHTTPClient(client *http.Client) *OrganizationsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the organizations params
func (o *OrganizationsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the organizations params
func (o *OrganizationsParams) WithAuthorization(authorization string) *OrganizationsParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the organizations params
func (o *OrganizationsParams) SetAuthorization(authorization string) {
	o.Authorization = authorization
}

// WriteToRequest writes these params to a swagger request
func (o *OrganizationsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Authorization
	if err := r.SetHeaderParam("Authorization", o.Authorization); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
