// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/TommyO/fabric.io/models"
)

// TimeInAppReader is a Reader for the TimeInApp structure.
type TimeInAppReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *TimeInAppReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewTimeInAppOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewTimeInAppOK creates a TimeInAppOK with default headers values
func NewTimeInAppOK() *TimeInAppOK {
	return &TimeInAppOK{}
}

/*TimeInAppOK handles this case with default header values.

Report
*/
type TimeInAppOK struct {
	Payload *models.TimeInAppOKBody
}

func (o *TimeInAppOK) Error() string {
	return fmt.Sprintf("[GET /api/v2/organizations/{organization_id}/apps/{app_id}/growth_analytics/time_in_app_per_dau.json][%d] timeInAppOK  %+v", 200, o.Payload)
}

func (o *TimeInAppOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.TimeInAppOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
