// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ActiveNowOKBody active now o k body
// swagger:model activeNowOKBody
type ActiveNowOKBody struct {
	ActiveNowOKBodyAllOf0

	DeltaReport
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *ActiveNowOKBody) UnmarshalJSON(raw []byte) error {

	var aO0 ActiveNowOKBodyAllOf0
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.ActiveNowOKBodyAllOf0 = aO0

	var aO1 DeltaReport
	if err := swag.ReadJSON(raw, &aO1); err != nil {
		return err
	}
	m.DeltaReport = aO1

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m ActiveNowOKBody) MarshalJSON() ([]byte, error) {
	var _parts [][]byte

	aO0, err := swag.WriteJSON(m.ActiveNowOKBodyAllOf0)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)

	aO1, err := swag.WriteJSON(m.DeltaReport)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO1)

	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this active now o k body
func (m *ActiveNowOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.ActiveNowOKBodyAllOf0.Validate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.DeltaReport.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *ActiveNowOKBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ActiveNowOKBody) UnmarshalBinary(b []byte) error {
	var res ActiveNowOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
