// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// App app
// swagger:model App
type App struct {

	// accounts count
	AccountsCount int64 `json:"accounts_count,omitempty"`

	// analytics app has received data
	AnalyticsAppHasReceivedData bool `json:"analytics_app_has_received_data,omitempty"`

	// analytics forward to google analytics
	AnalyticsForwardToGoogleAnalytics bool `json:"analytics_forward_to_google_analytics,omitempty"`

	// analytics include purchase events in forwarded events
	AnalyticsIncludePurchaseEventsInForwardedEvents bool `json:"analytics_include_purchase_events_in_forwarded_events,omitempty"`

	// base identifier
	BaseIdentifier string `json:"base_identifier,omitempty"`

	// bundle identifier
	BundleIdentifier string `json:"bundle_identifier,omitempty"`

	// collect analytics
	CollectAnalytics bool `json:"collect_analytics,omitempty"`

	// crashes count
	CrashesCount int64 `json:"crashes_count,omitempty"`

	// created at
	CreatedAt string `json:"created_at,omitempty"`

	// dashboard url
	DashboardURL string `json:"dashboard_url,omitempty"`

	// icon128 url
	Icon128URL string `json:"icon128_url,omitempty"`

	// icon32 url
	Icon32URL string `json:"icon32_url,omitempty"`

	// icon64 url
	Icon64URL string `json:"icon64_url,omitempty"`

	// icon hash
	IconHash string `json:"icon_hash,omitempty"`

	// icon url
	IconURL string `json:"icon_url,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// impacted devices count
	ImpactedDevicesCount int64 `json:"impacted_devices_count,omitempty"`

	// importance level
	ImportanceLevel int64 `json:"importance_level,omitempty"`

	// kit versions
	KitVersions string `json:"kit_versions,omitempty"`

	// latest build
	LatestBuild string `json:"latest_build,omitempty"`

	// map of available products
	MapOfAvailableProducts interface{} `json:"map_of_available_products,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// organization id
	OrganizationID string `json:"organization_id,omitempty"`

	// platform
	Platform string `json:"platform,omitempty"`

	// sdk kits
	SdkKits string `json:"sdk_kits,omitempty"`

	// status
	Status string `json:"status,omitempty"`

	// unresolved issues count
	UnresolvedIssuesCount int64 `json:"unresolved_issues_count,omitempty"`

	// watched
	Watched int64 `json:"watched,omitempty"`
}

// Validate validates this app
func (m *App) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *App) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *App) UnmarshalBinary(b []byte) error {
	var res App
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
