// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// BasicReport basic report
// swagger:model BasicReport
type BasicReport struct {

	// app id
	AppID string `json:"app_id,omitempty"`

	// build
	Build string `json:"build,omitempty"`

	// end
	End int64 `json:"end,omitempty"`

	// start
	Start int64 `json:"start,omitempty"`
}

// Validate validates this basic report
func (m *BasicReport) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *BasicReport) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *BasicReport) UnmarshalBinary(b []byte) error {
	var res BasicReport
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
