// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// DeltaReportDeltas delta report deltas
// swagger:model deltaReportDeltas
type DeltaReportDeltas struct {

	// week over week
	WeekOverWeek *DeltaReportDeltasWeekOverWeek `json:"week_over_week,omitempty"`
}

// Validate validates this delta report deltas
func (m *DeltaReportDeltas) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateWeekOverWeek(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DeltaReportDeltas) validateWeekOverWeek(formats strfmt.Registry) error {

	if swag.IsZero(m.WeekOverWeek) { // not required
		return nil
	}

	if m.WeekOverWeek != nil {

		if err := m.WeekOverWeek.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("week_over_week")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *DeltaReportDeltas) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DeltaReportDeltas) UnmarshalBinary(b []byte) error {
	var res DeltaReportDeltas
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
