// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// DeltaReport delta report
// swagger:model DeltaReport
type DeltaReport struct {

	// deltas
	Deltas *DeltaReportDeltas `json:"deltas,omitempty"`
}

// Validate validates this delta report
func (m *DeltaReport) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDeltas(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DeltaReport) validateDeltas(formats strfmt.Registry) error {

	if swag.IsZero(m.Deltas) { // not required
		return nil
	}

	if m.Deltas != nil {

		if err := m.Deltas.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("deltas")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *DeltaReport) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DeltaReport) UnmarshalBinary(b []byte) error {
	var res DeltaReport
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
