// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// DeltaReportDeltasWeekOverWeek delta report deltas week over week
// swagger:model deltaReportDeltasWeekOverWeek
type DeltaReportDeltasWeekOverWeek struct {

	// delta fraction
	DeltaFraction float64 `json:"delta_fraction,omitempty"`

	// last week value
	LastWeekValue float64 `json:"last_week_value,omitempty"`
}

// Validate validates this delta report deltas week over week
func (m *DeltaReportDeltasWeekOverWeek) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *DeltaReportDeltasWeekOverWeek) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DeltaReportDeltasWeekOverWeek) UnmarshalBinary(b []byte) error {
	var res DeltaReportDeltasWeekOverWeek
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
