// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// OAuthUnauthorizedBody o auth unauthorized body
// swagger:model oAuthUnauthorizedBody
type OAuthUnauthorizedBody struct {

	// error
	Error string `json:"error,omitempty"`

	// error description
	ErrorDescription string `json:"error_description,omitempty"`

	// status
	Status string `json:"status,omitempty"`
}

// Validate validates this o auth unauthorized body
func (m *OAuthUnauthorizedBody) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *OAuthUnauthorizedBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OAuthUnauthorizedBody) UnmarshalBinary(b []byte) error {
	var res OAuthUnauthorizedBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
