// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// Organization organization
// swagger:model Organization
type Organization struct {

	// accounts count
	AccountsCount int64 `json:"accounts_count,omitempty"`

	// alias
	Alias string `json:"alias,omitempty"`

	// api key
	APIKey string `json:"api_key,omitempty"`

	// apps counts
	AppsCounts interface{} `json:"apps_counts,omitempty"`

	// build secret
	BuildSecret string `json:"build_secret,omitempty"`

	// enrollments
	Enrollments interface{} `json:"enrollments,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// mopub id
	MopubID string `json:"mopub_id,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// sdk organization
	SdkOrganization bool `json:"sdk_organization,omitempty"`
}

// Validate validates this organization
func (m *Organization) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *Organization) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Organization) UnmarshalBinary(b []byte) error {
	var res Organization
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
