// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"bytes"
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// SeriesDateNumberSeriesTuple series date number series tuple
// swagger:model seriesDateNumberSeriesTuple
type SeriesDateNumberSeriesTuple struct {

	// p0
	// Required: true
	P0 int64 `json:"-"` // custom serializer

	// p1
	// Required: true
	P1 float64 `json:"-"` // custom serializer

}

// UnmarshalJSON unmarshals this tuple type from a JSON array
func (m *SeriesDateNumberSeriesTuple) UnmarshalJSON(raw []byte) error {
	// stage 1, get the array but just the array
	var stage1 []json.RawMessage
	buf := bytes.NewBuffer(raw)
	dec := json.NewDecoder(buf)
	dec.UseNumber()

	if err := dec.Decode(&stage1); err != nil {
		return err
	}

	// stage 2
	if len(stage1) > 0 {
		buf = bytes.NewBuffer(stage1[0])
		dec := json.NewDecoder(buf)
		dec.UseNumber()
		if err := dec.Decode(&m.P0); err != nil {
			return err
		}
	}
	if len(stage1) > 1 {
		buf = bytes.NewBuffer(stage1[1])
		dec := json.NewDecoder(buf)
		dec.UseNumber()
		if err := dec.Decode(&m.P1); err != nil {
			return err
		}
	}

	return nil
}

// MarshalJSON marshals this tuple type into a JSON array
func (m SeriesDateNumberSeriesTuple) MarshalJSON() ([]byte, error) {
	data := []interface{}{
		m.P0,
		m.P1,
	}

	return json.Marshal(data)
}

// Validate validates this series date number series tuple
func (m *SeriesDateNumberSeriesTuple) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateP0(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateP1(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SeriesDateNumberSeriesTuple) validateP0(formats strfmt.Registry) error {

	if err := validate.Required("0", "body", int64(m.P0)); err != nil {
		return err
	}

	return nil
}

func (m *SeriesDateNumberSeriesTuple) validateP1(formats strfmt.Registry) error {

	if err := validate.Required("1", "body", float64(m.P1)); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *SeriesDateNumberSeriesTuple) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SeriesDateNumberSeriesTuple) UnmarshalBinary(b []byte) error {
	var res SeriesDateNumberSeriesTuple
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
