// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// SessionsCountOKBody sessions count o k body
// swagger:model sessionsCountOKBody
type SessionsCountOKBody struct {

	// app id
	AppID string `json:"app_id,omitempty"`

	// builds
	Builds []string `json:"builds"`

	// end
	End int64 `json:"end,omitempty"`

	// sessions
	Sessions int64 `json:"sessions,omitempty"`

	// start
	Start int64 `json:"start,omitempty"`
}

// Validate validates this sessions count o k body
func (m *SessionsCountOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateBuilds(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SessionsCountOKBody) validateBuilds(formats strfmt.Registry) error {

	if swag.IsZero(m.Builds) { // not required
		return nil
	}

	return nil
}

// MarshalBinary interface implementation
func (m *SessionsCountOKBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SessionsCountOKBody) UnmarshalBinary(b []byte) error {
	var res SessionsCountOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
